config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :family_members
  resources :members
  resources :plans
  resources :counties
  resources :relationships
  resources :membership_fees
  resources :statuses
  resources :roles
  resources :genders
  resources :states
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'pages#home'


end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/county.rb
class County < ApplicationRecord
  belongs_to :state
  has_many :members

  def display_name
    county

  end
end

app/models/family_member.rb
class FamilyMember < ApplicationRecord

  scope :voter_list, ->{
    where('age > ?', 15)
  }

  belongs_to :member
  belongs_to :relationship
  belongs_to :gender
end

app/models/gender.rb
class Gender < ApplicationRecord

  has_many :members
  has_many :family_members

  def display_name
    gender

  end
end

app/models/member.rb
class Member < ApplicationRecord
  scope :active_members, -> {
    where(:status_id => 1)
  }

  scope :inactive_expired_membership, -> {
    where(:status_id => 2)
  }

  scope :send_card, ->{
    where(:send_card => true)
  }

  scope :do_not_send_card, ->{
    where(:send_card => false)
  }

  scope :paid, ->{
    where(:membership_fee_id => 1)
  }

  scope :payment_required, ->{
    where(:membership_fee_id => 2)
  }

  scope :voter_list, ->{
    where('age > ?', 15)
  }

  scope :lifetime_members, ->{
      where(:plan_id => 1)
  }

  scope :three_year_members, ->{
    where(:plan_id => 2)
  }

  scope :yearly_members, ->{
    where(:plan_id => 3)
  }




  belongs_to :gender
  belongs_to :county
  belongs_to :state
  belongs_to :plan
  belongs_to :membership_fee
  belongs_to :role
  belongs_to :status
  has_many   :family_member

  def display_name
    title
    first_name
    middle_initial
    last_name_string

  end


end

app/models/membership_fee.rb
class MembershipFee < ApplicationRecord
  has_many :members

  def display_name
    membership_fees_status

  end
end

app/models/plan.rb
class Plan < ApplicationRecord

  has_many :member

  def display_name
    membershipPlan

  end

  end

app/models/relationship.rb
class Relationship < ApplicationRecord
  has_many :family_member

  def display_name
    relation

  end
end

app/models/role.rb
class Role < ApplicationRecord
  has_many :members

  def display_name
    role

  end
end

app/models/state.rb
class State < ApplicationRecord
  has_many :counties
  has_many :members

  def display_name
    stateCode

  end
end

app/models/status.rb
class Status < ApplicationRecord

  has_many :members

  def display_name
    status

  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  end


end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  before_action :set_status, only: [:show, :edit, :update, :destroy]

  # GET /statuses
  # GET /statuses.json
  def index
    @statuses = Status.all
  end

  # GET /statuses/1
  # GET /statuses/1.json
  def show
  end

  # GET /statuses/new
  def new
    @status = Status.new
  end

  # GET /statuses/1/edit
  def edit
  end

  # POST /statuses
  # POST /statuses.json
  def create
    @status = Status.new(status_params)

    respond_to do |format|
      if @status.save
        format.html { redirect_to @status, notice: 'Status was successfully created.' }
        format.json { render :show, status: :created, location: @status }
      else
        format.html { render :new }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /statuses/1
  # PATCH/PUT /statuses/1.json
  def update
    respond_to do |format|
      if @status.update(status_params)
        format.html { redirect_to @status, notice: 'Status was successfully updated.' }
        format.json { render :show, status: :ok, location: @status }
      else
        format.html { render :edit }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statuses/1
  # DELETE /statuses/1.json
  def destroy
    @status.destroy
    respond_to do |format|
      format.html { redirect_to statuses_url, notice: 'Status was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_status
      @status = Status.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def status_params
      params.require(:status).permit(:status)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/counties_helper.rb
module CountiesHelper
end

app/helpers/genders_helper.rb
module GendersHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/views/statuses/_form.html.erb
<%= form_with(model: status, local: true) do |form| %>
  <% if status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(status.errors.count, "error") %> prohibited this status from being saved:</h2>

      <ul>
      <% status.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :status %>
    <%= form.text_field :status %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/statuses/edit.html.erb
<h1>Editing Status</h1>

<%= render 'form', status: @status %>

<%= link_to 'Show', @status %> |
<%= link_to 'Back', statuses_path %>

app/views/statuses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Statuses</h1>

<table>
  <thead>
    <tr>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @statuses.each do |status| %>
      <tr>
        <td><%= status.status %></td>
        <td><%= link_to 'Show', status %></td>
        <td><%= link_to 'Edit', edit_status_path(status) %></td>
        <td><%= link_to 'Destroy', status, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Status', new_status_path %>

app/views/statuses/new.html.erb
<h1>New Status</h1>

<%= render 'form', status: @status %>

<%= link_to 'Back', statuses_path %>

app/views/statuses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Status:</strong>
  <%= @status.status %>
</p>

<%= link_to 'Edit', edit_status_path(@status) %> |
<%= link_to 'Back', statuses_path %>