config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :family_members
  resources :members
  resources :plans
  resources :counties
  resources :relationships
  resources :membership_fees
  resources :statuses
  resources :roles
  resources :genders
  resources :states
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'pages#home'


end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/county.rb
class County < ApplicationRecord
  belongs_to :state
  has_many :members

  def display_name
    county

  end
end

app/models/family_member.rb
class FamilyMember < ApplicationRecord

  scope :voter_list, ->{
    where('age > ?', 15)
  }

  belongs_to :member
  belongs_to :relationship
  belongs_to :gender
end

app/models/gender.rb
class Gender < ApplicationRecord

  has_many :members
  has_many :family_members

  def display_name
    gender

  end
end

app/models/member.rb
class Member < ApplicationRecord
  scope :active_members, -> {
    where(:status_id => 1)
  }

  scope :inactive_expired_membership, -> {
    where(:status_id => 2)
  }

  scope :send_card, ->{
    where(:send_card => true)
  }

  scope :do_not_send_card, ->{
    where(:send_card => false)
  }

  scope :paid, ->{
    where(:membership_fee_id => 1)
  }

  scope :payment_required, ->{
    where(:membership_fee_id => 2)
  }

  scope :voter_list, ->{
    where('age > ?', 15)
  }

  scope :lifetime_members, ->{
      where(:plan_id => 1)
  }

  scope :three_year_members, ->{
    where(:plan_id => 2)
  }

  scope :yearly_members, ->{
    where(:plan_id => 3)
  }




  belongs_to :gender
  belongs_to :county
  belongs_to :state
  belongs_to :plan
  belongs_to :membership_fee
  belongs_to :role
  belongs_to :status
  has_many   :family_member

  def display_name
    title
    first_name
    middle_initial
    last_name_string

  end


end

app/models/membership_fee.rb
class MembershipFee < ApplicationRecord
  has_many :members

  def display_name
    membership_fees_status

  end
end

app/models/plan.rb
class Plan < ApplicationRecord

  has_many :member

  def display_name
    membershipPlan

  end

  end

app/models/relationship.rb
class Relationship < ApplicationRecord
  has_many :family_member

  def display_name
    relation

  end
end

app/models/role.rb
class Role < ApplicationRecord
  has_many :members

  def display_name
    role

  end
end

app/models/state.rb
class State < ApplicationRecord
  has_many :counties
  has_many :members

  def display_name
    stateCode

  end
end

app/models/status.rb
class Status < ApplicationRecord

  has_many :members

  def display_name
    status

  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  end


end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :set_relationship, only: [:show, :edit, :update, :destroy]

  # GET /relationships
  # GET /relationships.json
  def index
    @relationships = Relationship.all
  end

  # GET /relationships/1
  # GET /relationships/1.json
  def show
  end

  # GET /relationships/new
  def new
    @relationship = Relationship.new
  end

  # GET /relationships/1/edit
  def edit
  end

  # POST /relationships
  # POST /relationships.json
  def create
    @relationship = Relationship.new(relationship_params)

    respond_to do |format|
      if @relationship.save
        format.html { redirect_to @relationship, notice: 'Relationship was successfully created.' }
        format.json { render :show, status: :created, location: @relationship }
      else
        format.html { render :new }
        format.json { render json: @relationship.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /relationships/1
  # PATCH/PUT /relationships/1.json
  def update
    respond_to do |format|
      if @relationship.update(relationship_params)
        format.html { redirect_to @relationship, notice: 'Relationship was successfully updated.' }
        format.json { render :show, status: :ok, location: @relationship }
      else
        format.html { render :edit }
        format.json { render json: @relationship.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /relationships/1
  # DELETE /relationships/1.json
  def destroy
    @relationship.destroy
    respond_to do |format|
      format.html { redirect_to relationships_url, notice: 'Relationship was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_relationship
      @relationship = Relationship.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def relationship_params
      params.require(:relationship).permit(:relation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/counties_helper.rb
module CountiesHelper
end

app/helpers/genders_helper.rb
module GendersHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/views/relationships/_form.html.erb
<%= form_with(model: relationship, local: true) do |form| %>
  <% if relationship.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(relationship.errors.count, "error") %> prohibited this relationship from being saved:</h2>

      <ul>
      <% relationship.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :relation %>
    <%= form.text_field :relation %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/relationships/edit.html.erb
<h1>Editing Relationship</h1>

<%= render 'form', relationship: @relationship %>

<%= link_to 'Show', @relationship %> |
<%= link_to 'Back', relationships_path %>

app/views/relationships/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Relationships</h1>

<table>
  <thead>
    <tr>
      <th>Relation</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @relationships.each do |relationship| %>
      <tr>
        <td><%= relationship.relation %></td>
        <td><%= link_to 'Show', relationship %></td>
        <td><%= link_to 'Edit', edit_relationship_path(relationship) %></td>
        <td><%= link_to 'Destroy', relationship, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Relationship', new_relationship_path %>

app/views/relationships/new.html.erb
<h1>New Relationship</h1>

<%= render 'form', relationship: @relationship %>

<%= link_to 'Back', relationships_path %>

app/views/relationships/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Relation:</strong>
  <%= @relationship.relation %>
</p>

<%= link_to 'Edit', edit_relationship_path(@relationship) %> |
<%= link_to 'Back', relationships_path %>