config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :family_members
  resources :members
  resources :plans
  resources :counties
  resources :relationships
  resources :membership_fees
  resources :statuses
  resources :roles
  resources :genders
  resources :states
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'pages#home'


end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/county.rb
class County < ApplicationRecord
  belongs_to :state
  has_many :members

  def display_name
    county

  end
end

app/models/family_member.rb
class FamilyMember < ApplicationRecord

  scope :voter_list, ->{
    where('age > ?', 15)
  }

  belongs_to :member
  belongs_to :relationship
  belongs_to :gender
end

app/models/gender.rb
class Gender < ApplicationRecord

  has_many :members
  has_many :family_members

  def display_name
    gender

  end
end

app/models/member.rb
class Member < ApplicationRecord
  scope :active_members, -> {
    where(:status_id => 1)
  }

  scope :inactive_expired_membership, -> {
    where(:status_id => 2)
  }

  scope :send_card, ->{
    where(:send_card => true)
  }

  scope :do_not_send_card, ->{
    where(:send_card => false)
  }

  scope :paid, ->{
    where(:membership_fee_id => 1)
  }

  scope :payment_required, ->{
    where(:membership_fee_id => 2)
  }

  scope :voter_list, ->{
    where('age > ?', 15)
  }

  scope :lifetime_members, ->{
      where(:plan_id => 1)
  }

  scope :three_year_members, ->{
    where(:plan_id => 2)
  }

  scope :yearly_members, ->{
    where(:plan_id => 3)
  }




  belongs_to :gender
  belongs_to :county
  belongs_to :state
  belongs_to :plan
  belongs_to :membership_fee
  belongs_to :role
  belongs_to :status
  has_many   :family_member

  def display_name
    title
    first_name
    middle_initial
    last_name_string

  end


end

app/models/membership_fee.rb
class MembershipFee < ApplicationRecord
  has_many :members

  def display_name
    membership_fees_status

  end
end

app/models/plan.rb
class Plan < ApplicationRecord

  has_many :member

  def display_name
    membershipPlan

  end

  end

app/models/relationship.rb
class Relationship < ApplicationRecord
  has_many :family_member

  def display_name
    relation

  end
end

app/models/role.rb
class Role < ApplicationRecord
  has_many :members

  def display_name
    role

  end
end

app/models/state.rb
class State < ApplicationRecord
  has_many :counties
  has_many :members

  def display_name
    stateCode

  end
end

app/models/status.rb
class Status < ApplicationRecord

  has_many :members

  def display_name
    status

  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  end


end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  before_action :set_plan, only: [:show, :edit, :update, :destroy]

  # GET /plans
  # GET /plans.json
  def index
    @plans = Plan.all
  end

  # GET /plans/1
  # GET /plans/1.json
  def show
  end

  # GET /plans/new
  def new
    @plan = Plan.new
  end

  # GET /plans/1/edit
  def edit
  end

  # POST /plans
  # POST /plans.json
  def create
    @plan = Plan.new(plan_params)

    respond_to do |format|
      if @plan.save
        format.html { redirect_to @plan, notice: 'Plan was successfully created.' }
        format.json { render :show, status: :created, location: @plan }
      else
        format.html { render :new }
        format.json { render json: @plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /plans/1
  # PATCH/PUT /plans/1.json
  def update
    respond_to do |format|
      if @plan.update(plan_params)
        format.html { redirect_to @plan, notice: 'Plan was successfully updated.' }
        format.json { render :show, status: :ok, location: @plan }
      else
        format.html { render :edit }
        format.json { render json: @plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plans/1
  # DELETE /plans/1.json
  def destroy
    @plan.destroy
    respond_to do |format|
      format.html { redirect_to plans_url, notice: 'Plan was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_plan
      @plan = Plan.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def plan_params
      params.require(:plan).permit(:Membership_plan, :price, :currency)
    end
end

app/controllers/states_controller.rb
class StatesController < ApplicationController
  before_action :set_state, only: [:show, :edit, :update, :destroy]

  # GET /states
  # GET /states.json
  def index
    @states = State.all
  end

  # GET /states/1
  # GET /states/1.json
  def show
  end

  # GET /states/new
  def new
    @state = State.new
  end

  # GET /states/1/edit
  def edit
  end

  # POST /states
  # POST /states.json
  def create
    @state = State.new(state_params)

    respond_to do |format|
      if @state.save
        format.html { redirect_to @state, notice: 'State was successfully created.' }
        format.json { render :show, status: :created, location: @state }
      else
        format.html { render :new }
        format.json { render json: @state.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /states/1
  # PATCH/PUT /states/1.json
  def update
    respond_to do |format|
      if @state.update(state_params)
        format.html { redirect_to @state, notice: 'State was successfully updated.' }
        format.json { render :show, status: :ok, location: @state }
      else
        format.html { render :edit }
        format.json { render json: @state.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /states/1
  # DELETE /states/1.json
  def destroy
    @state.destroy
    respond_to do |format|
      format.html { redirect_to states_url, notice: 'State was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_state
      @state = State.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def state_params
      params.require(:state).permit(:stateCode, :stateName)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/counties_helper.rb
module CountiesHelper
end

app/helpers/genders_helper.rb
module GendersHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/views/states/_form.html.erb
<%= form_with(model: state, local: true) do |form| %>
  <% if state.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(state.errors.count, "error") %> prohibited this state from being saved:</h2>

      <ul>
      <% state.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :stateCode %>
    <%= form.text_field :stateCode %>
  </div>

  <div class="field">
    <%= form.label :stateName %>
    <%= form.text_field :stateName %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/states/edit.html.erb
<h1>Editing State</h1>

<%= render 'form', state: @state %>

<%= link_to 'Show', @state %> |
<%= link_to 'Back', states_path %>

app/views/states/index.html.erb
<p id="notice"><%= notice %></p>

<h1>States</h1>

<table>
  <thead>
    <tr>
      <th>Statecode</th>
      <th>Statename</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @states.each do |state| %>
      <tr>
        <td><%= state.stateCode %></td>
        <td><%= state.stateName %></td>
        <td><%= link_to 'Show', state %></td>
        <td><%= link_to 'Edit', edit_state_path(state) %></td>
        <td><%= link_to 'Destroy', state, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New State', new_state_path %>

app/views/states/new.html.erb
<h1>New State</h1>

<%= render 'form', state: @state %>

<%= link_to 'Back', states_path %>

app/views/states/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Statecode:</strong>
  <%= @state.stateCode %>
</p>

<p>
  <strong>Statename:</strong>
  <%= @state.stateName %>
</p>

<%= link_to 'Edit', edit_state_path(@state) %> |
<%= link_to 'Back', states_path %>